// <auto-generated />
using System;
using Gestion_Conge.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Gestion_Conge.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    partial class ProjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Gestion_Conge.Models.Collaborateur", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<string>("fonctionidf")
                        .HasColumnType("text");

                    b.Property<string>("idSup")
                        .HasColumnType("text");

                    b.Property<string>("mdp")
                        .HasColumnType("text");

                    b.Property<string>("picture")
                        .HasColumnType("text");

                    b.Property<string>("roleidr")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("fonctionidf");

                    b.HasIndex("roleidr");

                    b.ToTable("Collaborateurs");
                });

            modelBuilder.Entity("Gestion_Conge.Models.conge", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Congeid")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("dateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("statusids")
                        .HasColumnType("text");

                    b.Property<string>("typeidc")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Congeid");

                    b.HasIndex("statusids");

                    b.HasIndex("typeidc");

                    b.ToTable("conges");
                });

            modelBuilder.Entity("Gestion_Conge.Models.fonctionCollaborateur", b =>
                {
                    b.Property<string>("idf")
                        .HasColumnType("text");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("label")
                        .HasColumnType("text");

                    b.HasKey("idf");

                    b.ToTable("fonctionCollaborateurs");
                });

            modelBuilder.Entity("Gestion_Conge.Models.role", b =>
                {
                    b.Property<string>("idr")
                        .HasColumnType("text");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("label")
                        .HasColumnType("text");

                    b.HasKey("idr");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Gestion_Conge.Models.statusConge", b =>
                {
                    b.Property<string>("ids")
                        .HasColumnType("text");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("label")
                        .HasColumnType("text");

                    b.HasKey("ids");

                    b.ToTable("statusConges");
                });

            modelBuilder.Entity("Gestion_Conge.Models.typeConge", b =>
                {
                    b.Property<string>("idc")
                        .HasColumnType("text");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("label")
                        .HasColumnType("text");

                    b.HasKey("idc");

                    b.ToTable("typeConges");
                });

            modelBuilder.Entity("Gestion_Conge.Models.Collaborateur", b =>
                {
                    b.HasOne("Gestion_Conge.Models.fonctionCollaborateur", "fonction")
                        .WithMany()
                        .HasForeignKey("fonctionidf");

                    b.HasOne("Gestion_Conge.Models.role", "role")
                        .WithMany()
                        .HasForeignKey("roleidr");

                    b.Navigation("fonction");

                    b.Navigation("role");
                });

            modelBuilder.Entity("Gestion_Conge.Models.conge", b =>
                {
                    b.HasOne("Gestion_Conge.Models.conge", "Conge")
                        .WithMany()
                        .HasForeignKey("Congeid");

                    b.HasOne("Gestion_Conge.Models.statusConge", "status")
                        .WithMany()
                        .HasForeignKey("statusids");

                    b.HasOne("Gestion_Conge.Models.typeConge", "type")
                        .WithMany()
                        .HasForeignKey("typeidc");

                    b.Navigation("Conge");

                    b.Navigation("status");

                    b.Navigation("type");
                });
#pragma warning restore 612, 618
        }
    }
}
